plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "de.akaflieg_freiburg.enroute.wear"
    compileSdk = 36

    defaultConfig {
        applicationId = "de.akaflieg_freiburg.enroute.wear"

        // Wear OS 3.0. Wear OS 2 (API 25-28) could only be distributed by embedding the
        // watch APK inside the phone APK, and the phone APK here is generated by
        // androiddeployqt from a Gradle project that does not exist in the repository, so
        // that route is not available to us at all. API 30 is therefore the floor, not a
        // preference. It covers every watch sold new in the last several years.
        minSdk = 30
        targetSdk = 36

        versionCode = 1
        versionName = "0.1.0"

        resourceConfigurations += listOf("en", "de")

        ndk {
            // The map renderer ships native code for four architectures and every
            // Wear OS device sold to date is 32-bit ARM -- the Galaxy Watch 7 reports
            // "armeabi-v7a,armeabi" and nothing else. Shipping the other three would
            // treble the size of the APK with code no watch can run.
            abiFilters += "armeabi-v7a"
        }
    }

    buildTypes {
        debug {
            // So a development build can sit next to a release build on the same watch.
            applicationIdSuffix = ".debug"
            isMinifyEnabled = false
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Bytecode target 17, deliberately not jvmToolchain(17): the development machine has
    // JDK 21 only, and a toolchain request would try to provision a JDK over the network.
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    buildFeatures {
        compose = true
    }

    lint {
        abortOnError = true
        warningsAsErrors = false
    }

    packaging {
        resources.excludes += setOf("/META-INF/{AL2.0,LGPL2.1}")
    }
}

// The companion protocol exists so that this app needs no proprietary Google library.
// Fail the build rather than let one arrive through a transitive dependency.
configurations.configureEach {
    exclude(group = "com.google.android.gms")
    exclude(group = "com.google.android.support", module = "wearable")
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    implementation(libs.wear.compose.material3)
    implementation(libs.wear.compose.foundation)
    implementation(libs.wear.compose.navigation)

    // The same renderer the phone app uses, so the watch draws the pilot's own map
    // rather than an imitation of it. BSD-2-Clause.
    implementation(libs.maplibre.android)

    // Only to hand the renderer a client that presents the pairing code. The renderer
    // fetches every tile itself and the sole way to attach a header to those requests
    // is to give it an OkHttp client, so the alternative would be a credential in the
    // URL -- which the protocol rules out, because a URL ends up in logs.
    //
    // The nav transport still uses java.net on purpose: this arrived with the map, and
    // a dependency that arrives with one feature should not quietly become the app's
    // default for everything.
    implementation(libs.okhttp)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
}
